GET  http://localhost:25156/api/stats/commands/?cmds=true
User-Agent: "Menhera-FODA"
content-type: application/json

{
             "authorName" : "req.body.authorName",
             "authorId" : "req.body.authorName",
             "guildName": "req.body.authorName",
             "guildId" : "req.body.authorName",
             "commandName": "req.body.authorName",
             "data": "req.body.authorName"
}